####  PBS preamble
#PBS -N Mothur.batch
#PBS -M rprops@umich.edu
#PBS -m abe

#PBS -l nodes=1:ppn=10,mem=250gb,walltime=10:00:00
#PBS -V

#PBS -A vdenef_fluxm
#PBS -l qos=flux
#PBS -q fluxm
####  End PBS preamble

#  Show list of CPUs you ran on, if you're running under PBS
if [ -n "$PBS_NODEFILE" ]; then cat $PBS_NODEFILE; fi

#  Change to the directory you submitted from
if [ -n "$PBS_O_WORKDIR" ]; then cd $PBS_O_WORKDIR; fi
pwd

## Choose taxonomy of interest for oligotyping (if none leave it at Bacteria)
## Example: Bacteria;Firmicutes;
sed -i "s/Bacteria/Bacteria;Proteobacteria;Betaproteobacteria;Burkholderiales;betI;betI_A/g" mothur.batch.taxass

# Create stability file
paste <(ls *R1*.fastq | awk -F"_" '{print $1}') <(ls *R1*.fastq) <(ls *R2*.fastq) > stability.file

# Run Mothur
mothur mothur.batch.taxass
